name: Upload Version File
description: 'Upload Version File'
inputs:
  version:
    required: true
    description: 'version for further reference'
  env:
    required: true
    description: 'To add with version file name'

runs:
  using: "composite"
  steps:
    - name: Save variable as artifact
      shell: bash
      run: |
        VERSION=${{ inputs.version }}
        echo $VERSION > version

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: 'version-${{ inputs.env }}'
        path: version
