name: Base Flutter Web Deploy
on:
  workflow_call:
    inputs:
      versionToBuild:
        required: true
        type: string
      environment:
        required: true
        type: string
    secrets:
        REPO_TOKEN:
            required: true
        EC2_IP:
            required: true
        AWS_ACCESS_KEY:
            required: true
        AWS_SECRET_KEY:
            required: true
        AWS_REGION:
            required: true
        EC2_USER:
            required: true
        SECURITY_GROUP_ID:
            required: true
        SSH_PRIVATE_KEY_FOR_EC2:
            required: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    steps:
      - name: Check out only flutterFlow web folder
        uses: actions/checkout@v4
        with:
          repository: WonderWhyDev/wonderWhy
          token: ${{ secrets.REPO_TOKEN }}
          fetch-depth: 1
          sparse-checkout: 'flutterFlow/magnum'
          sparse-checkout-cone-mode: false
          ref : test_server_deploy
          version: ${{ inputs.versionToBuild }}
            
      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.5

      - run: |
          cd flutterFlow/magnum
          sed -i 's|<base href="/">|<base href="/flutterflow/">|' web/index.html
          flutter clean
          flutter pub get         
          flutter build web --release --web-renderer html
          
      - name: Brotli compress
        run: |
          sudo apt-get  -y install brotli
          cd flutterFlow/magnum/build/web
          rm -rf canvaskit
          find ./ -type f -exec brotli -jZv {} \;
          
      - run: |
          cd flutterFlow/magnum/build/
          zip -r web.zip web

      - uses: ./.github/actions/copy_to_ec2
        with:
           ec2IP: ${{ secrets.EC2_IP }}
           awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY }}
           awsSecretKey: ${{ secrets.AWS_SECRET_KEY }}
           awsRegion: ${{ secrets.AWS_REGION }}
           ec2User: ${{ secrets.EC2_USER }}
           securityGroupId: ${{ secrets.SECURITY_GROUP_ID }}
           sshKey: ${{ secrets.SSH_PRIVATE_KEY_FOR_EC2 }}
           fileToCopy: flutterFlow/magnum/build/web.zip
           destination: ~/web.zip
           unzipDestination: ~/


