name: Base Zitadel Deploy
on:
  workflow_call:
    inputs:
      versionToBuild:
        required: true
        type: string
      environment:
        required: true
        type: string
    secrets:
        REPO_TOKEN:
            required: true
        EC2_IP:
            required: true
        AWS_ACCESS_KEY:
            required: true
        AWS_SECRET_KEY:
            required: true
        AWS_REGION:
            required: true
        EC2_USER:
            required: true
        SECURITY_GROUP_ID:
            required: true
        SSH_PRIVATE_KEY_FOR_EC2:
            required: true
        CA_CERTS_FULL_CHAIN:
            required: true
        CA_CERTS_PRIVATE_KEY:
            required: true

jobs:
  deploy_zitadel:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    steps:
      - name: check out repository for actions
        uses: actions/checkout@v4

      - name: Check out only zitadel folder
        uses: actions/checkout@v4
        with:
          repository: WonderWhyDev/wonderWhy
          token: ${{ secrets.REPO_TOKEN }}
          path: wonderWhy
          fetch-depth: 1
          sparse-checkout: 'zitadel'
          sparse-checkout-cone-mode: false
          ref :  ${{ inputs.versionToBuild }}

      - run: |
          cd wonderWhy
          ls -lsh
          mkdir -p zitadel/certs
          echo "${{ secrets.CA_CERTS_FULL_CHAIN }}" > zitadel/certs/fullchain.pem  
          echo "${{ secrets.CA_CERTS_PRIVATE_KEY }}" > zitadel/certs/privkey.pem 
          zip -r zitadel.zip zitadel

      - uses: ./.github/actions/copy_to_ec2
        with:
           ec2IP: ${{ secrets.EC2_IP }}
           awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY }}
           awsSecretKey: ${{ secrets.AWS_SECRET_KEY }}
           awsRegion: ${{ secrets.AWS_REGION }}
           ec2User: ${{ secrets.EC2_USER }}
           securityGroupId: ${{ secrets.SECURITY_GROUP_ID }}
           sshKey: ${{ secrets.SSH_PRIVATE_KEY_FOR_EC2 }}
           fileToCopy: ./wonderWhy/zitadel.zip
           destination: ~/zitadel.zip
           unzipDestination: ~/
           runScript: |
             cd zitadel
             sh deploy.sh



