name: Base Flutter Web Deploy
on:
  workflow_call:
    inputs:
      versionToBuild:
        required: true
        type: string
      environment:
        required: true
        type: string
    secrets:
        REPO_TOKEN:
            required: true
        EC2_IP:
            required: true
        AWS_ACCESS_KEY:
            required: true
        AWS_SECRET_KEY:
            required: true
        AWS_REGION:
            required: true
        EC2_USER:
            required: true
        SECURITY_GROUP_ID:
            required: true
        SSH_PRIVATE_KEY_FOR_EC2:
            required: true
        OAUTH_CLIENT_ID:
            required: true
        OAUTH_CLIENT_SECRET:
            required: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    steps:
      - name: check out repository for actions
        uses: actions/checkout@v4

      - name: Check out application code
        uses: actions/checkout@v4
        with:
          repository: WonderWhyDev/wonderWhy
          token: ${{ secrets.REPO_TOKEN }}
          path: wonderWhy
          fetch-depth: 1
          ref :  ${{ inputs.versionToBuild }}

      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.5

      - uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: 'wonderWhy/yarn.lock'

      - name: build react web
        run: |
          cd wonderWhy
          yarn install
          rm -rf web/.env
          touch web/.env
          echo "CLIENT_ID=${{ secrets.OAUTH_CLIENT_ID }}" >> web/.env
          echo "CLIENT_SECRET=${{ secrets.OAUTH_CLIENT_SECRET }}" >> web/.env
          yarn workspace web build
          mkdir -p webDeploy/reactWeb
          mv web/dist webDeploy/reactWeb

      - name: build flutter flow web
        run: |
          cd wonderWhy/flutterFlow/magnum
          flutter clean
          flutter pub get         
          flutter build web --release --web-renderer html
          mv build/web ../../webDeploy/
          mv ../../webDeploy/web ../../webDeploy/ffWeb

      - name: Brotli compress
        run: |
          cd wonderWhy/webDeploy
          sudo apt-get  -y install brotli
          find ./ -type f -exec brotli -jZkv {} \;

      - run: |
          cd wonderWhy
          zip -r webDeploy.zip webDeploy

      - uses: ./.github/actions/copy_to_ec2
        with:
           ec2IP: ${{ secrets.EC2_IP }}
           awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY }}
           awsSecretKey: ${{ secrets.AWS_SECRET_KEY }}
           awsRegion: ${{ secrets.AWS_REGION }}
           ec2User: ${{ secrets.EC2_USER }}
           securityGroupId: ${{ secrets.SECURITY_GROUP_ID }}
           sshKey: ${{ secrets.SSH_PRIVATE_KEY_FOR_EC2 }}
           fileToCopy: ./wonderWhy/webDeploy.zip
           destination: ~/webDeploy.zip
           unzipDestination: ~/
           scriptToRun: |
             cd webDeploy
             sudo rm -rf ~/nginx/html
             mkdir ~/nginx/html
             mkdir ~/nginx/html/re
             sudo cp -r ffWeb/* ~/nginx/html/
             sudo cp -r reactWeb/* ~/nginx/html/re/
             


