name: Magnum Web Deploy
run-name: Magnum Web Deploy
on:
  workflow_call:
    inputs:
      latest_version:
        required: true
        type: string
      token:
        required: true
        description: Repo Read Token

jobs:
  magnum-web-deploy:
    uses: ./.github/workflows/base_web_deploy.yml
    needs: find_latest_version
    with:
      versionToBuild: ${{ inputs.latest_version }}
      environment: magnum
    secrets:
        REPO_TOKEN: ${{ inputs.token }}
        EC2_IP: ${{ secrets.EC2_IP }}
        AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        EC2_USER: ${{ secrets.EC2_USER }}
        SECURITY_GROUP_ID: ${{ secrets.SECURITY_GROUP_ID }}
        SSH_PRIVATE_KEY_FOR_EC2: ${{ secrets.SSH_PRIVATE_KEY_FOR_EC2 }}
        OAUTH_CLIENT_ID: ${{ secrets.OAUTH_CLIENT_ID }}
        OAUTH_CLIENT_SECRET: ${{ secrets.OAUTH_CLIENT_SECRET }}