name: Magnum backend Deploy
run-name: Magnum backend Deploy
on:
  workflow_dispatch:
    # inputs:
    #   latest_version:
    #     required: true
    #     type: string

jobs:
  find_latest_version:
    uses: ./.github/workflows/base_get_latest_repo_version.yml
    with:
      environment: magnum
    secrets:
      REPO_TOKEN: ${{ secrets.REPO_READ_TOKEN }}

  validate_backend:
    runs-on: ubuntu-latest
    environment:
      name: magnum
    steps:
      - name: check out repository for actions
        uses: actions/checkout@v4

      - name: Check out only flutterFlow web folder
        uses: actions/checkout@v4
        with:
          repository: WonderWhyDev/wonderWhy
          token: ${{ secrets.REPO_READ_TOKEN }}
          path: wonderWhy
          fetch-depth: 1
          ref:  ${{ needs.find_latest_version.outputs.latest_version }}

      - uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: 'wonderWhy/yarn.lock'
      - run: |
          cd wonderWhy
          yarn install
          yarn b format
          yarn b lint
          yarn b build
      - uses: ./.github/actions/upload_version_file
        with:
          ref:  ${{ needs.find_latest_version.outputs.latest_version }}

      - run: |
          mkdir backend
          cp -r wonderWhy/backend/prisma backend/
          cp wonderWhy/backend/dist/app.js backend/
          cp wonderWhy/backend/package.json backend/
          cp wonderWhy/backend/deploy/* backend/
          zip -r backend.zip backend

      - uses: ./.github/actions/copy_to_ec2
        with:
          ec2IP: ${{ secrets.EC2_IP }}
          awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY }}
          awsSecretKey: ${{ secrets.AWS_SECRET_KEY }}
          awsRegion: ${{ secrets.AWS_REGION }}
          ec2User: ${{ secrets.EC2_USER }}
          securityGroupId: ${{ secrets.SECURITY_GROUP_ID }}
          sshKey: ${{ secrets.SSH_PRIVATE_KEY_FOR_EC2 }}
          fileToCopy: ./backend.zip
          destination: ~/backend.zip
          unzipDestination: ~/
          runScript: |
            cd backend
            sh deploy.sh ${{ secrets.OAUTH_CLIENT_ID }} ${{ secrets.OAUTH_CLIENT_SECRET }}