name: QA Flutter Web Deploy
run-name: ${{ github.actor }} - ${{ github.event.head_commit.message }} commit is running
on:
  workflow_dispatch:

jobs:
  find_latest_version:
    uses: ./.github/workflows/base_workflows/get_latest_repo_version.yml
    with:
      environment: qa
    secrets:
      REPO_TOKEN: ${{ secrets.REPO_READ_TOKEN }}

  qa-flutter-flow-web-deploy:
    uses: ./.github/workflows/base_workflows/flutter_web_deploy.yml
    needs: find_latest_version
    with:
      versionToBuild: ${{ needs.find_latest_version.outputs.latest_version }}
      environment: qa
    secrets:
        REPO_TOKEN: ${{ secrets.REPO_READ_TOKEN }}
        EC2_IP: ${{ secrets.EC2_IP }}
        AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        EC2_USER: ${{ secrets.EC2_USER }}
        SECURITY_GROUP_ID: ${{ secrets.SECURITY_GROUP_ID }}
        SSH_PRIVATE_KEY_FOR_EC2: ${{ secrets.SSH_PRIVATE_KEY_FOR_EC2 }}