name: QA Flutter Web Deploy
run-name: ${{ github.actor }} - ${{ github.event.head_commit.message }} commit is running
on:
  workflow_dispatch:

jobs:
  find_latest_version:
    uses: ./.github/workflows/base_get_latest_repo_version.yml
    secrets:
      repoToken: ${{ secrets.REPO_READ_TOKEN }}
  qa-flutter-flow-web-deploy:
    uses: ./.github/workflows/base_flutter_web_deploy.yml
    needs: find_latest_version
    with:
      versionToBuild: ${{ needs.find_latest_version.outputs.latest_version }}
      environment: qa
